sk/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from sk.views import * 

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^login/', 'django.contrib.auth.views.login'),
	(r'^auth/', include('auth.urls')),

	(r'^$', landing),
	(r'^upload/$', upload),
	(r'^passport/(?P<user_id>\d+)/$', passport),	
	(r'^item/(?P<item_id>\d+)/$', item),
	(r'^follow/(?P<user_id>\d+)/$', follow),
	(r'^unfollow/(?P<user_id>\d+)/$', unfollow),
	(r'^vote/(?P<item_id>\d+)/(?P<user_id>\d+)/$', vote),
	(r'^fetch/(?P<item_type>[a-z]*)/$', fetch),

	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
	(r'^comments/', include('django.contrib.comments.urls')),
	url(r'^admin/', include(admin.site.urls)),
)

sk/sooouk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django import forms

	
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	about_me = models.TextField()
	followers = models.ManyToManyField("self", null=True, symmetrical=False, related_name="following")
	created_at = models.DateTimeField(auto_now_add = True)
	def __unicode__(self):
		return self.user.username	

#EXTENDING THE USER PROFILE
def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
       profile, created = UserProfile.objects.get_or_create(user=instance)  

post_save.connect(create_user_profile, sender=User) 

class CategoryType(models.Model):
	category = models.CharField(max_length = 100)
	created_at = models.DateTimeField(auto_now_add = True)
	def __unicode__(self):
		return self.title	

# class CategoryItem(models.Model):
# 	category = models.CharField(max_length = 100)
# 	created_at = models.DateTimeField(auto_now_add = True)
# 	def __unicode__(self):
# 		return self.title
		
class Item(models.Model):
	user = models.ForeignKey(UserProfile)
	title = models.CharField(max_length = 128)
	post = models.TextField()
	photourl = models.CharField(max_length = 500)
	location = models.CharField(max_length = 200)
	#convert location on redirect to item full page after creation 
	latitude = models.CharField(max_length = 100)
	longitude = models.CharField(max_length = 100)
	country = models.CharField(max_length = 100)
	product_type = models.CharField(max_length = 100)
	created_at = models.DateTimeField(auto_now_add = True)
	item_size = models.IntegerField();
	def __unicode__(self):
		return self.title

class Vote(models.Model):
	item = models.ForeignKey(Item)
	voter = models.ForeignKey(UserProfile)
	def __unicode__(self):
		return self.item.title

class UploadForm(forms.Form):
	#category_choices = [(m.id, m.category) for c in Categories.objects.all()]
	title = forms.CharField(max_length = 100)
	post = forms.CharField(widget=forms.Textarea)
	location = forms.CharField(max_length = 200)
	photourl = forms.CharField(max_length = 500)
    #categories = forms.MultipleChoiceField(required=True, label='Item Category', choices=maintainer_choices)
	
	
class PassportForm(forms.Form):
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)
	about_me = forms.CharField(widget=forms.Textarea)		

sk/sooouk/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

def landing(request):
	return render_to_response('sooouk/index.html', context_instance=RequestContext(request))

sk/templates/sooouk/index.html
{% extends 'base.html'%}

{% block css %}
<link href="{{MEDIA_URL}}css/style-index.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{MEDIA_URL}}js/index.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.isotope.min.js"></script>
{%endblock%}

{% block portal %}
<div class="portal">
	{% if user.is_authenticated %}
		<a href="/auth/logout/">Logout</a>
	{% else %}
		<a href="/login/">Login</a>
	{% endif %}
</div>
{% endblock %}



{% block header_left %}
			<div class="filterbar">
				<ul id="filters" class="option-set clearfix" data-option-key="filter">
				  <li><a href="#" data-filter="*">Show All</a></li>
				  <li id="countries">Countries</li>
				  <li id="categories">Categories</li>
				  <li id="people">People</li>
				  <li><a href="#" data-filter=".random">Random</a></li>
				</ul>
			</div>
			<div class="filterbar" id="countriesfilter">
				<ul id="filters" class="option-set clearfix" data-option-key="filter">
				  <li><a href="#" data-filter=".france">France</a></li>
				  <li><a href="#" data-filter=".spain">Spain</a></li>
				  <li><a href="#" data-filter=".bolivia">Bolivia</a></li>
				  <li><a href="#" data-filter=".china">China</a></li>
				  <li><a href="#" data-filter=".japan">Japan</a></li>
				  <li><a href="#" data-filter=".india">India</a></li>
				  <li><a href="#" data-filter=".uganda">Uganda</a></li>
				  <li><a href="#" data-filter=".botswana">Botswana</a></li>
				</ul>
			</div>
			<div class="filterbar" id="categoriesfilter">
				<ul id="filters" class="option-set clearfix" data-option-key="filter">
				  <li><a href="#" data-filter=".Food">Food</a></li>
				  <li><a href="#" data-filter=".Clothing">Clothing</a></li>
				  <li><a href="#" data-filter=".Beauty">Beauty</a></li>
				  <li><a href="#" data-filter=".Household">Household</a></li>
				  <li><a href="#" data-filter=".Recreation">Recreation</a></li>
				  <li><a href="#" data-filter=".Drink">Drink</a></li>
				</ul>
			</div>
			<div class="subfilterbar" id="peoplefilter">
				<ul class="subfilters" class="option-set clearfix" data-option-key="filter">
					to be articulated...
				</ul>
			</div>
{% endblock %}


{% block content_left %}
	{% if latest_item_list %}
		<ul class="items">
			{% for item in latest_item_list %}
			<a href="/item/{{item.id}}">
				<li class="item {{item.product_type}} {{item.location}}">
					<div class="title">{{item.title}}</div>
					<img class="prod_img" src="{{item.photourl}}" width="130" height="130"/>
				</li>
			</a>
			{%endfor%}
		</ul>
		<div style="clear: both;"></div>
	{% else %}
		<p>Problem getting Items...</p>
	{% endif %}

	<script type="text/javascript">
	
	$(function(){
	      
	      var $container = $('#content');
	
	      $container.isotope({
	        itemSelector : '.item',
	        layoutMode : 'fitRows'
	      });
	      
	      
			$('#filters a').click(function(){
				var selector = $(this).attr('data-filter');
				$container.isotope({ filter: selector });
				return false;
			});
	
	      
	    });
	</script>
{% endblock %}

sk/templates/sooouk/item.html
{% extends 'base_fixed.html'%}


{% block head %}
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<link href="{{MEDIA_URL}}css/style_item.css" rel="stylesheet" type="text/css" />
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
	var address = "{{item.location}}";
	var itemUserId = {{item.user.user.id}};
	var voter = {{user.id}};
	
/*
IF I EVER GET BACK TO BRANDON KONKLE'S COMMENT SYSTEM http://brandonkonkle.com/blog/2009/feb/16/ajax-django-comments-jquery/

$(document).ready(function() {
	    media = '{{MEDIA_URL}}';
	    $('div.comment-form form').submit(function() {
	        ajaxComment({'media': media});
	        return false;
    });
});

*/	

</script>
<script type="text/javascript" src="{{MEDIA_URL}}js/loadMap.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/item.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/follow.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/vote.js"></script>
<script src="{{ MEDIA_URL }}ajaxcomments/js/post-comment.js" type="text/javascript"></script>

{% endblock %}



{% block portal %}
<div class="portal">
	{% if user.is_authenticated %}
		<a href="/auth/logout/">Logout</a>
	{% else %}
		<a href="/login/">Login</a>
	{% endif %}
</div>
{% endblock %}



{% block left_fixed %}
{% if item %}
	<div class="itemfull">
		<div class="itemfullvisual">
			<img src="{{item.photourl}}" alt="{{item.title}}" class="itemfullphoto" />
			<div id="map_canvas" style="width:100%; height:300px; float: left; z-index:0;"></div>
		</div>
		
		<div class="itembanner">
			<div class="itemfulltitle">
				{{item.title}}	
			</div>
			
			<div class="right">
			
				<div id="votearea">
				{% if user.is_authenticated %}
					{% if user != item.user.user %}
						{% if hasVoted%}
							<b>{{item.vote_set.count}}</b> Vote{{item.vote_set.count|pluralize}}
							<div>You have Voted.</div>
						{% else %}
							{{item.vote_set.count}} Vote{{item.vote_set.count|pluralize}}
							<button type="submit" class="votebutton">Vote</button>
						{%endif%}
					{% else %}
						{{item.vote_set.count}} Vote{{item.vote_set.count|pluralize}}
							
					{% endif %}
				{% else %}
				{% endif %}
				</div>	

			
				<div class="tweet">
					<a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out Sooouk >> http://soooukitup.tumblr.com/" data-count="horizontal" data-via="sooouk">Tweet</a>
					<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
			</div>	
		</div>
		
		<div class="itemfullpost">
			{{item.post}}
		</div>
		{% if user.is_authenticated %}
			{% if user != item.user.user %}
			<div class="postedby">
				Posted by <a id="user" href="/passport/{{item.user.user.id}}/">{{item.user.user.username}}</a> 
			</div>
				{% if isFollowing%}
				<button type="submit" class="unfollowbutton">Unfollow</button>
				{% else %}
				<button type="submit" class="followbutton">Follow</button>	
				{% endif %}
			{% else %}
			<div class="postedby">This item was uploaded by you.</div>		
			{% endif %}
		{% else %}
			<div class="postedby">
				Posted by <a id="user" href="/passport/{{item.user.user.id}}/">{{item.user.user.username}}</a> 
			</div>
			
			<form action="/login/">
				<button type="submit" class="loginbutton">login</button>
			</form>			
		{% endif %}	

	{% else %}
		<p>Item doesn't exist.</p>
	{% endif %}
	
	{% load comments %}
	{% render_comment_form for item %}
	{% render_comment_list for item %}
	
	</div>

{% endblock %}

sk/templates/sooouk/passport.html
{% extends 'base.html'%}


{% block head %}
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<link href="{{MEDIA_URL}}css/style_passport.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
var address = "New York City";	

function changeUserInfo(){
	$.ajax({
		url: url,
		type:"POST",
		data:{'word': word},
		success: function(data){
			try{
				$("#word").val("")
				var jsonOBJ = $.parseJSON(data);
				var forCSS = jsonOBJ.word;
				if($("#word-"+forCSS).length > 0){
					console.log("it found the existing element");
					$("#word-"+forCSS).html( jsonOBJ.word + " <b style=\"color: #28b8ff;\">x "+ jsonOBJ.count +"</b>")
				}else{
					$(".words").append("<div class=\"word\"><a id=\"word-"+ forCSS +"\" style=\"cursor:pointer;\">"+jsonOBJ.word +" <b style=\"color: #28b8ff;\">x "+jsonOBJ.count +"</b></a></div>");
				}
			}
			catch(e){
				console.log("not cool");
			}
		}		
	});
}

$(document).ready(function() {	
	var userInfoOpen = false;
	
	function openClose(){
		if(userInfoOpen == false){
			$('.passportform').show(200);
			$('.passportinfo').hide(200);			
			userInfoOpen = true;
		}else if(userInfoOpen == true){
			$('.passportform').hide(200);
			$('.passportinfo').show(200);	
			userInfoOpen = false;
		}
	}

	$("button").click(function(){
		if($(this).attr('id') == 'edit'){
			openClose();
		}else if($(this).attr('id')=='passportbutton'){
			changeUserInfo()
		}
	});
	
	$('#passportbutton').submit(function(event){
		event.preventDefault(); 
		return false;
	});

});
</script>
<script type="text/javascript" src="{{MEDIA_URL}}js/loadMap.js"></script>

{% endblock %}



{% block portal %}
<div class="portal">
	{% if user.is_authenticated %}
		<a href="/auth/logout/">Logout</a>
	{% else %}
		<a href="/login/">Login</a>
	{% endif %}
</div>
{% endblock %}



{% block content %}
<div class="passportinfo">
	<div>
		<img src="{{MEDIA_URL}}/img/blank_avatar.png" alt="avatar" class="avatarbig"/>
	</div>
	<div>
		User Name:
		{{profile.user.username}}
	</div>
	<div>
		First Name:
		{{profile.user.first_name}}
	</div>
	<div>
		Last Name:
		{{profile.user.last_name}}
	</div>
	<div>
		About Me:
		{{profile.about_me}}
	</div>
	
	{% if user == profile.user %}
	<button id="edit">Edit Info</button>
	{% endif %}
	<div id="map_canvas" style="width:100%; height:200px; float: right;"></div>
</div>

<div class="passportform">
	<button id="edit">Don't edit</button>
	{% if error %}
	<p class="formerror">   
	{{ error }}
	</p>   
	{% endif %}
	<form method="post" action=".">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit" id="passportbutton">Save Changes</button>
	</form>
</div>

{% if my_item_list %}
	{% for item in latest_item_list %}
	<a href="/item/{{item.id}}">
		<div class="item">
			<img src="{{item.photourl}}" style="width: 100%; height: 100%;"/>
			<div class="itemtitle">
				{{item.title}}
			</div>
			{% if item.user.user.username == user.username %}
				Uploaded by You
			{% else %}
				{{item.user.user.username}}
			{% endif %}
		</div>
	</a>
	{% endfor %}
{% endif %}

{% if my_item_following_list %}
	{% for item in latest_item_list %}
	<a href="/item/{{item.id}}">
		<div class="item">
			<img src="{{item.photourl}}" style="width: 100%; height: 100%;"/>
			<div class="itemtitle">
				{{item.title}}
			</div>
			{% if item.user.user.username == user.username %}
				Uploaded by You
			{% else %}
				{{item.user.user.username}}
			{% endif %}
		</div>
	</a>
	{% endfor %}
{% endif %}
{% endblock %}

sk/templates/sooouk/upload.html
{% extends 'base.html'%}


{% block head %}

{% endblock %}



{% block portal %}

<div class="portal">
	{% if user.is_authenticated %}
		<a href="/auth/logout/">Logout</a>
	{% else %}
		<a href="/login/">Login</a>
	{% endif %}
</div>

{% endblock %}




{% block content %}

	<div class="uploadform">
		{% if error %}
		<p class="formerror">   
		{{ error }}
		</p>   
		{% endif %}
		<form method="post" action=".">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit" id="signupbutton">Upload Product</button>
		</form>
	</div>

{% endblock %}